### ISSUE TITLE
HSup constraint as a type predicate

### ISSUE THREAD

**Issue by dorchard** [granule-project/granule#182]
We should be able to capture Hsup constraints as type predicates, e.g.
```
myPush : forall {a : Type, b : Type, r : s, s : Semiring} . {HSupRel r r r} => (Product a b) [r] -> Product (a [r]) (b [r])
myPush [Prod a b] = Prod [a] [b]
```
Which could compile down to the `HSup` constraint in the checker. This would be useful for deriving `push` as well.

**Comment by jackohughes** [comment]
As @dorchard said, maybe instead of `HSupRel` being a ternary relation on `r r r`, it would be better to have some constraint e.g. `Pushable r` which compiles down to this ternary relation under the hood, but only requires the programmer to specify the grade once? I'm not sure off the top of my head if there are instances where we would want/need to allow these elements of the relation to be different grades.

**Comment by dorchard** [comment]
This has now been provided by `c ⨱ c` but we could do with a non-unicode version like `Pushable r` as an alias!
