### ISSUE TITLE
Odd Error

### ISSUE THREAD

**Issue by heades** [granule-project/granule#77]
Hi, everyone.

Check out this program:

```
iso : forall (a : Type, b : Type, r : Nat=, s : Nat=) . (a |r| -> b) -> (b |s| -> a) -> (a |1| -> a)
iso f g |x| = g |(f |x|)|
```

I am getting a very odd error message:

```
Unbound variable error: :2:19:
  Type variable `kprom_(.0` is unbound (not quantified).
Error type checking examples/Monoidal.gr
```

I have also tried:

```
iso : forall (a : Type, b : Type, r : Nat=, s : Nat=) . (a |r| -> b) -> (b |s| -> a) -> (a |1| -> a)
iso f g |x| = let y = f |x| in (g |y|)
```

Yields:

```
Unbound variable error: :2:36:
  Type variable `kprom_y.1` is unbound (not quantified).
Error type checking examples/Monoidal.gr
```

The first one seems to think that `(` is a variable name, and the latter thinks `y` is unbound, but it is bound.

**Comment by dorchard** [comment]
Both of these examples had type errors but also the messages given were not very good at all, exposing guys of the type checker. The appears of `(` in the variable name is just due to some internal fresh name generation. 

I believe the correct implementation you want is:

```
iso : forall (a : Type, b : Type, r : Nat, s : Nat) . (a [r] -> b) [s] -> (b [s] -> a) -> (a [r*s] -> a)
iso [f] g [x] = g [f [x]]
```
But the error messages have improved a lot now.

**Comment by buggymcbugfix** [comment]
Yess, so much more readable with brackets!!
